### ISSUE TITLE
AUR-Build fails

### ISSUE THREAD

**Issue by andreaseckmayr** [simenheg/zatackax#1]
==> Making package: zatackax-git 0.3.1.r1.g350fdb4-1 (Tue 11 Feb 2020 02:35:26 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating zatackax git repo...
Fetching origin
  -> Found path-for-game-data.patch
  -> Found zatackax.png
  -> Found zatackax.desktop
==> Validating source files with sha256sums...
    zatackax ... Skipped
    path-for-game-data.patch ... Passed
    zatackax.png ... Passed
    zatackax.desktop ... Passed
==> Extracting sources...
  -> Creating working copy of zatackax git repo...
Reset branch 'makepkg'
==> Starting prepare()...
total 12
drwxr-xr-x 3 andreas andreas 4096 Feb 11 14:35 .
drwxr-xr-x 5 andreas andreas 4096 Feb  4 23:28 ..
lrwxrwxrwx 1 andreas andreas   58 Feb 11 14:35 path-for-game-data.patch -> /home/andreas/Builds/zatackax-git/path-for-game-data.patch
drwxr-xr-x 5 andreas andreas 4096 Feb  4 23:28 zatackax
lrwxrwxrwx 1 andreas andreas   50 Feb 11 14:35 zatackax.desktop -> /home/andreas/Builds/zatackax-git/zatackax.desktop
lrwxrwxrwx 1 andreas andreas   46 Feb 11 14:35 zatackax.png -> /home/andreas/Builds/zatackax-git/zatackax.png
patching file common.h
patching file sound.c
Hunk #1 FAILED at 52.
Hunk #2 FAILED at 77.
2 out of 2 hunks FAILED -- saving rejects to file sound.c.rej
patching file zatackax.c
Hunk #1 FAILED at 2274.
Hunk #2 FAILED at 2291.
Hunk #3 succeeded at 2313 (offset -334 lines).
Hunk #4 FAILED at 2656.
Hunk #5 FAILED at 2664.
4 out of 5 hunks FAILED -- saving rejects to file zatackax.c.rej
patching file zatackax.h
Hunk #1 succeeded at 7 with fuzz 1.

**Comment by simenheg** [comment]
Hi @andreaseckmayr, thanks for reporting.

Unfortunately I have no control over the Zatacka X package entry at the AUR. It looks like the maintainer needs to rebase their custom patch `path-for-game-data.patch` on the current master branch. I'd suggest you file an issue for it over at the AUR.

**Comment by andreaseckmayr** [comment]
Thanks, I will move it to the AUR.
